{% set heapster_memory = "300Mi" -%}
{% set num_nodes = pillar.get('num_nodes', -1) -%}
{% if num_nodes >= 0 -%}
  {% set heapster_memory = (200 + num_nodes * 12)|string + "Mi" -%}
{% endif -%}

apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v14
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v14
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v14
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v14
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.20.0-alpha4
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: {{ heapster_memory }}
            requests:
              cpu: 100m
              memory: {{ heapster_memory }}
          command:
            - /heapster
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --metric_resolution=60s
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
        - image: gcr.io/google_containers/heapster:v0.20.0-alpha4
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: {{ heapster_memory }}
            requests:
              cpu: 100m
              memory: {{ heapster_memory }}
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=gcl
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
