apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v15
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v15
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v15
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v15
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.20.0-alpha11
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --sink=gcm:?metrics=autoscaling
            - --metric_resolution=60s
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: usrsharecacerts
              mountPath: /usr/share/ca-certificates
              readOnly: true
        - image: gcr.io/google_containers/heapster:v0.20.0-alpha11
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=gcl
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: usrsharecacerts
              mountPath: /usr/share/ca-certificates
              readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: usrsharecacerts
          hostPath:
            path: /usr/share/ca-certificates